services:
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa1234
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local