services:
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa1234
      - POSTGRES_DB=POSTGRES
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'marcan@mail.com'
      PGADMIN_DEFAULT_PASSWORD: "sa1234"
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  db:
    driver: local